config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  resources :eletronics
  resources :eletronics
  resources :things
  resources :clothes
  get 'static_pages/home'

  devise_for :users
	root :to => "static_pages#home"

end

app/models/clothe.rb
class Clothe < ActiveRecord::Base
	def self.search(search)
		where("name LIKE ?", "%#{search}%")
		where("content LIKE ?", "%#{search}%")
	end
end

app/models/eletronic.rb
class Eletronic < ActiveRecord::Base
	def self.search(search)
		where("name LIKE ?", "%#{search}%")
		where("content LIKE ?", "%#{search}%")
	end
end

app/models/thing.rb
class Thing < ActiveRecord::Base
	def self.search(search)
		where("name LIKE ?", "%#{search}%")
		where("content LIKE ?", "%#{search}%")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def is_logged_in?
    unless user_signed_in?
      access_denied
    end
    true
  end

  def access_denied
    @message = "Você precisa estar logado para cadastrar um novo item."

    render :template => 'layouts/_access_denied', :status => 403, :formats => [:html]
  end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :set_clothe, only: [:show, :edit, :update, :destroy]
  before_filter :is_logged_in?, only: [:edit, :update, :destroy, :new, :create]

  # GET /clothes
  # GET /clothes.json
  def index
    @clothes = Clothe.all
  end
	
  # GET /clothes/1
  # GET /clothes/1.json
  def show
  end

  # GET /clothes/new
  def new
    @clothe = Clothe.new
  end

  # GET /clothes/1/edit
  def edit
  end

  # POST /clothes
  # POST /clothes.json
  def create
    @clothe = Clothe.new(clothe_params)

    respond_to do |format|
      if @clothe.save
        format.html { redirect_to @clothe, notice: 'Clothe was successfully created.' }
        format.json { render :show, status: :created, location: @clothe }
      else
        format.html { render :new }
        format.json { render json: @clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clothes/1
  # PATCH/PUT /clothes/1.json
  def update
    respond_to do |format|
      if @clothe.update(clothe_params)
        format.html { redirect_to @clothe, notice: 'Clothe was successfully updated.' }
        format.json { render :show, status: :ok, location: @clothe }
      else
        format.html { render :edit }
        format.json { render json: @clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clothes/1
  # DELETE /clothes/1.json
  def destroy
    @clothe.destroy
    respond_to do |format|
      format.html { redirect_to clothes_url, notice: 'Clothe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clothe
      @clothe = Clothe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clothe_params
      params.require(:clothe).permit(:name, :color, :tissue, :tamanho)
    end
end

app/controllers/eletronics_controller.rb
class EletronicsController < ApplicationController
  before_action :set_eletronic, only: [:show, :edit, :update, :destroy]
  before_filter :is_logged_in?, only: [:edit, :update, :destroy, :new, :create]

  # GET /eletronics
  # GET /eletronics.json
  def index
    @eletronics = Eletronic.all
  end

  # GET /eletronics/1
  # GET /eletronics/1.json
  def show
  end

  # GET /eletronics/new
  def new
    @eletronic = Eletronic.new
  end

  # GET /eletronics/1/edit
  def edit
  end

  # POST /eletronics
  # POST /eletronics.json
  def create
    @eletronic = Eletronic.new(eletronic_params)

    respond_to do |format|
      if @eletronic.save
        format.html { redirect_to @eletronic, notice: 'Eletronic was successfully created.' }
        format.json { render :show, status: :created, location: @eletronic }
      else
        format.html { render :new }
        format.json { render json: @eletronic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eletronics/1
  # PATCH/PUT /eletronics/1.json
  def update
    respond_to do |format|
      if @eletronic.update(eletronic_params)
        format.html { redirect_to @eletronic, notice: 'Eletronic was successfully updated.' }
        format.json { render :show, status: :ok, location: @eletronic }
      else
        format.html { render :edit }
        format.json { render json: @eletronic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eletronics/1
  # DELETE /eletronics/1.json
  def destroy
    @eletronic.destroy
    respond_to do |format|
      format.html { redirect_to eletronics_url, notice: 'Eletronic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eletronic
      @eletronic = Eletronic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eletronic_params
      params.require(:eletronic).permit(:name, :year, :brand)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	search_token = params[:search][:search]
  	@result = []
  	@result << Clothe.find_by_name(search_token)
  	@result << Thing.find_by_name(search_token)
  	@result << Eletronic.find_by_name(search_token)

  	return @result
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	@eletronics = Eletronic.all
	@clothes = Clothe.all
	@things = Thing.all
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_filter :is_logged_in?, only: [:edit, :update, :destroy, :new, :create]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end
	
  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/eletronics_helper.rb
module EletronicsHelper
end

app/helpers/founded_objects_helper.rb
module FoundedObjectsHelper
end

app/helpers/foundedobject_helper.rb
module FoundedobjectHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/thing_helper.rb
module ThingHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/clothes/_form.html.erb
<%= bootstrap_form_for(@clothe) do |f| %>
  <% if @clothe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clothe.errors.count, "error") %> prohibited this clothe from being saved:</h2>

      <ul>
      <% @clothe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name %>
    <%= f.text_field :color %>
    <%= f.text_field :tissue %>
    <%= f.text_field :tamanho %>
    <center><%= f.submit %></center>

<% end %>

app/views/clothes/edit.html.erb
<h1>Editing Clothe</h1>

<%= render 'form' %>

<center><%= link_to 'Back', clothes_path %></center>

app/views/clothes/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Clothes</h3>

<div class="bt-right">
 <div class="pull-right">
    <%= button_to new_clothe_path, class: 'btn btn-success', :method=> :get do %>
      <i class="glyphicon glyphicon-plus", aria-hidden="true"></i> New Clothes
    <% end %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      	<th>Name</th>
     	<th>Color</th>
      	<th>Tissue</th>
      	<th>Tamanho</th>
      	<th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clothes.each do |clothe| %>
      <tr>
		<td><%= clothe.name %></td>
        <td><%= clothe.color %></td>
        <td><%= clothe.tissue %></td>
        <td><%= clothe.tamanho %></td>
        <right><td><%= button_to clothe, class: 'btn btn-default', :method=> :get do %>
          <i class="glyphicon glyphicon-eye-open"> Show</i>
        <% end %></td>
        <td><%= button_to edit_clothe_path(clothe), class: 'btn btn-primary', :method=> :get do %>
          <i class="glyphicon glyphicon-pencil"> Edit</i>
        <% end %></td>
        <td><%= button_to clothe, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger' do %>
          <i class="glyphicon glyphicon-trash"> Destroy</i>
        <% end %></td></right>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clothes/new.html.erb
<h1>New Clothe</h1>

<%= render 'form' %>

<%= button_to clothes_path, class: 'btn btn-default', :method=> :get do %>
	Back
<% end %>

app/views/clothes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clothe.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @clothe.color %>
</p>

<p>
  <strong>Tissue:</strong>
  <%= @clothe.tissue %>
</p>

<p>
  <strong>Size:</strong>
  <%= @clothe.tamanho %>
</p>

<center><%= link_to 'Edit', edit_clothe_path(@clothe) %> |
<%= link_to 'Back', clothes_path %></center>

app/views/eletronics/_form.html.erb
<%= bootstrap_form_for(@eletronic) do |f| %>
  <% if @eletronic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eletronic.errors.count, "error") %> prohibited this eletronic from being saved:</h2>

      <ul>
      <% @eletronic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name %>
    <%= f.text_field :year %>
    <%= f.text_field :brand %>
    <center><%= f.submit %></center>

<% end %>

app/views/eletronics/edit.html.erb
<h1>Editing Eletronic</h1>

<%= render 'form' %>

<center><%= link_to 'Back', eletronics_path %></center>

app/views/eletronics/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Eletronics</h3>
<div class="bt-right">
	<div class="pull-right">
		<%= button_to new_eletronic_path, class: 'btn btn-success', :method=> :get do %>
			<i class="glyphicon glyphicon-plus", aria-hidden="true"></i> New Eletronic
		<% end %>
	</div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eletronics.each do |eletronic| %>
      <tr>
        <td><%= eletronic.name %></td>
        <td><%= eletronic.year %></td>
        <td><%= eletronic.brand %></td>
        <right><td><%= button_to eletronic, class: 'btn btn-default', :method=> :get do %>
            <i class="glyphicon glyphicon-eye-open"> Show</i>
          <% end %></td>
        <td><%= button_to edit_eletronic_path(eletronic), class: 'btn btn-primary', :method=> :get do %>
          <i class="glyphicon glyphicon-pencil"> Edit</i>
        <% end %></td></right>
        <td><%= button_to eletronic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
           <i class="glyphicon glyphicon-trash"> Destroy</i>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/eletronics/new.html.erb
<h1>New Eletronic</h1>

<%= render 'form' %>

<%= button_to eletronics_path, class: 'btn btn-default', :method=> :get do %>
	Back
<% end %>

app/views/eletronics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @eletronic.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @eletronic.year %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @eletronic.brand %>
</p>

<center><%= link_to 'Edit', edit_eletronic_path(@eletronic) %> |
<%= link_to 'Back', eletronics_path %></center>

app/views/layouts/_access_denied.html.erb
<div class="alert alert-warning" role="alert">
	<%= @message %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Achados e Perdidos</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
	</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://localhost:3000/">Achados e Perdidos</a>
    </div>
  	<%= form_for :search, method: :get, url: search_index_path, html: { class: "navbar-form navbar-right" }  do |f| %>
			<div class="form-group">
				<%= f.text_field :search %>
			</div>
			<% f.submit %>
  	<% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"> Usuário </span><span class="caret"></span></a>
          <ul class="dropdown-menu">
           <% if user_signed_in? %>
      			Logged in as <strong><%= current_user.email %></strong><br>
      			<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
      			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
    		<% else %>
      			<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> </li>
      			<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
    		<% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div id="main-container" class="container">
      <div class="row">
		<div class="text-center">
			<%= link_to image_tag("achadosbannerfinal.png"), root_path %>
		</div>
		<div class="col-xs-2">
			<div class="opc">
				<div class="row">
					<%= button_to eletronics_path, class: 'btn btn-success', :method=> :get do %>
						Eletronics
					<% end %>
				</div>
				<div class="row">
					<%= button_to clothes_path, class: 'btn btn-success', :method=> :get do %>
						Clothes
					<% end %>
				</div>
				<div class="row">
					<%= button_to things_path, class: 'btn btn-success', :method=> :get do %>
						Other Things
					<% end %>
				</div>
			</div>
		</div>

		<div class="col-xs-8">
			<%= yield %>
			<div class="col-xs-12">
				<p class="text-justify">
				<i>Essa aplicação comunitária tem por objetivo auxiliar alunos da Faculdade do Gama a reencontrarem objetos perdidos.</i>
				</p>
			</div>
      	</div>
	</div>
</div>
</body>
</html>

app/views/search/index.html.erb
<table class="table">
	<thead>
		<th>Name</th>
		<th>Type</th>
	</thead>
	<tbody>
		<% @result.each do |result| %>
			<% unless result.nil? %>
				<tr>
					<td><%= link_to result.name, result %></td>
					<td><%= result.class.to_s %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/static_pages/home.html.erb
<h3>Lost objects</h3>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @eletronics.each do |eletronic| %>
      <tr>
        <td class="nome"><%= link_to eletronic.name, eletronic %></td>
        <td class="nome"><%= eletronic.year %></td>
        <td class="nome"><%= eletronic.brand %></td>
      </tr>
    <% end %>

		<% @clothes.each do |clothe| %>
      <tr>
			  <td class="nome"><%= link_to clothe.name.capitalize, clothe %></td>
        <td class="nome"><%= clothe.color.capitalize %></td>
			  <td class="nome"><%= clothe.tissue.capitalize %></td>
			  <td class="nome"><%= clothe.tamanho.capitalize %></td>
      </tr>
	<% end %>

	<% @things.each do |thing| %>
      <tr>
			<td class="nome"><a href=""><%= link_to thing.name.capitalize, thing %></td></a>
      </tr>
	<% end %>

  </tbody>
</table>

<br>

app/views/things/_form.html.erb
<%= bootstrap_form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name %>
    <center><%= f.submit %></center>

<% end %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form' %>

<center><%= link_to 'Back', things_path %></center>

app/views/things/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Things</h3>

<div class="bt-right">
 <div class="pull-right">
    <%= button_to new_thing_path, class: 'btn btn-success', :method=> :get do %>
      <i class="glyphicon glyphicon-plus", aria-hidden="true"></i> New Thing
    <% end %>
  </div>
</div>


<table class="table">
  <thead>
    <tr>
			<th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
	<td class="nome"><%= thing.name %></td>

        <right><td><%= button_to thing, class: 'btn btn-default', :method=> :get do %>
           <i class="glyphicon glyphicon-eye-open"> Show</i>
        <% end %></td>
        <td><%= button_to edit_thing_path(thing), class: 'btn btn-primary', :method=> :get do %>
           <i class="glyphicon glyphicon-pencil"> Edit</i>
        <% end %></td>
        <td><%= button_to thing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
           <i class="glyphicon glyphicon-trash"> Destroy</i>
        <% end %></td></right>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form' %>

<%= button_to  things_path, class: 'btn btn-default', :method=> :get do %>
	Back
<% end %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<center><%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %></center>